export const CONNECT_REQUESTED = 'CONNECT_REQUESTED';
export const CONNECT_SUCCEEDED = 'CONNECT_SUCCEEDED';
export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_GET_ALL = 'MESSAGE_GET_ALL';
